# Generated by Django 5.0.3 on 2024-05-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='password',
            new_name='email',
        ),
    ]
