# Generated by Django 5.0.3 on 2024-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_logs', '0002_rename_password_customer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('phone_no', models.CharField(max_length=20)),
                ('customer_id', models.CharField(max_length=200)),
            ],
        ),
    ]
