# Generated by Django 5.0.3 on 2024-05-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_logs', '0005_alter_cartproducts_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='product',
            field=models.IntegerField(),
        ),
    ]
