# Generated by Django 5.0.3 on 2024-05-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_logs', '0007_rename_price_cartproducts_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='total_price',
            field=models.IntegerField(blank=True),
        ),
    ]
