# Generated by Django 5.0.3 on 2024-05-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_logs', '0008_alter_cartproducts_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
