# Generated by Django 5.0.4 on 2024-05-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_logs", "0009_alter_cartproducts_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="payment_status",
            field=models.CharField(default="Not Paid", max_length=20),
        ),
        migrations.AddField(
            model_name="cart",
            name="shipment_status",
            field=models.CharField(default="In progress...", max_length=20),
        ),
    ]
